---
title: "R Notebook"
output: html_notebook
---

```{r}
source(here::here("RScripts", "InitialProcessing_2.R"))
```

```{r}
source("ChesapeakePersonalLibrary.R")
```

```{r}
library(vegan)
```

```{r}
countMat <-  nonSpikes %>%
  pivot_wider(id_cols = ID, names_from = ASV, values_from = reads, values_fill = 0) %>%
  column_to_rownames("ID") %>% as.matrix()
```




```{r}
seqDep <- countMat %>% apply(1, sum)
min(seqDep)
```

```{r}
countRare <- rrarefy(countMat, min(seqDep))
```


```{r}
conMult <- correctionData %>% column_to_rownames("ID") %>% .[countRare %>% rownames(),"conversionMultiplier"]
```

abundance per liter data table but rarified
```{r}
abunRareified <- sweep(countRare, MARGIN = 1, conMult, `*`)
```

```{r}
sampleAr <- sample %>%
  filter(ID %in% rownames(abunRareified)) %>%
  arrange(match(ID, rownames(abunRareified))) %>%
  mutate(Station_Depth = str_c(Station, Depth, sep = "_"))
```

Need developer verison of vegan for groups argument
```{r}
gamma <- diversity(abunRareified, groups = sampleAr$Station_Depth)
```

```{r}
gamma
```


```{r}
all_alpha <- diversity(abunRareified)
```

```{r}
mean_alpha <- tibble(sample = names(all_alpha), alpha = all_alpha, Station_Depth = sampleAr$Station_Depth)%>% 
  group_by(Station_Depth) %>%
  summarise(alpha = mean(alpha)) %>%
  identity()
mean_alpha
```


```{r}
abgDf <- left_join(enframe(gamma) %>% rename(gamma = value, Station_Depth = name),
          mean_alpha, by = "Station_Depth") %>%
  mutate(beta = gamma/alpha) %>%
  separate(Station_Depth, into = c("Station", "Depth"), sep = "_") %>%
  left_join(stations01 %>% select(Station, lat, long), by = "Station")
abgDfLong <- abgDf %>%
  pivot_longer(gamma:beta, names_to = "index", values_to = "value")
```

```{r}
abgDfLong %>%
  filter(Depth != "Oxy") %>%
  filter(index != "beta") %>%
  ggplot(aes(x = lat, y = value, shape = index, color = index)) + geom_point() + facet_wrap(~Depth, nrow = 2) +
  scale_color_manual(values = c(alpha = "black", gamma = "red"))
```
```{r}
abgDfLong %>%
  filter(Depth != "Oxy") %>%
  filter(index == "beta") %>%
  ggplot(aes(x = lat, y = value)) + geom_point() + facet_wrap(~Depth, nrow = 2) +
  geom_hline(yintercept = 1)
```

I'm not sure what to make of this.